# Generated by Django 4.0.4 on 2022-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(default=1, max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
