# Generated by Django 4.0.4 on 2022-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactprofile_phone_contactprofile_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
