# Generated by Django 4.0.4 on 2022-05-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='Phone',
            new_name='phone',
        ),
    ]
